FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
            cmake \
            libgflags-dev \
            libgoogle-glog-dev \
            libgtest-dev \
            libssl-dev \
            git \
            g++ \
            build-essential \
            curl

RUN git clone https://github.com/google/s2geometry.git

WORKDIR /s2geometry

RUN cmake -DBUILD_SHARED_LIBS=OFF . && make && make install

RUN mkdir /mason
WORKDIR /mason
RUN curl -sSfL https://github.com/mapbox/mason/archive/v0.20.0.tar.gz | tar -z --extract --strip-components=1 --exclude="*md" --exclude="test*" --directory=/mason

WORKDIR /code

RUN /mason/mason install geojson 0.4.3
RUN /mason/mason install geometry 1.0.0
RUN /mason/mason install variant 1.1.4
RUN /mason/mason install rapidjson 1.1.0

COPY ./nomad.3.9.1 /nomad
WORKDIR /nomad
ENV NOMAD_HOME=/nomad
RUN ./configure && make

WORKDIR /
RUN git clone https://github.com/ompl/ompl.git
RUN apt-get -y install cmake \
                    pkg-config \
                    libboost-serialization-dev \
                    libboost-filesystem-dev \
                    libboost-system-dev \
                    libboost-program-options-dev \
                    libboost-test-dev \
                    libeigen3-dev \
                    libode-dev
WORKDIR /ompl
RUN mkdir build && cd build && cmake .. && make install

WORKDIR /code


